[package]
name = "runner"
version = "0.1.0"
edition = "2024"

[dependencies]
bollard = "0.19"
hyper = { version = "0.14", features = ["client", "http1", "tcp"] }
hyperlocal = "0.8"
sandbox = { path = "../sandbox" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["rt", "time"] }
toml = "0.8"
tracing = "0.1"
types = { path = "../types" }
