[package]
name = "wasm-guest"
version = "0.1.1"
edition = "2024"

[[bin]]
name = "oxydra_wasm_guest"
path = "src/main.rs"

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
base64 = "0.22"

[profile.release]
opt-level = "z"
strip = true
lto = true
