[package]
name = "tools"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["time"] }
types = { path = "../types" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
