[package]
name = "memory"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
libsql = "0.9"
serde_json = "1"
types = { path = "../types" }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
